### ISSUE TITLE
Is it possible to cache assets loaded via xhr?

### ISSUE THREAD

**Issue by morenoh149** [ianmcgregor/assets-loader#8]
I'm using assets-loader to load assets from s3. I've properly added the `Cache-Control` header to all assets in my bucket. Digging through the source I see this lib pulls in the assets over xhr XMLHttpRequest. Is there a way to let the browser cache previously loaded assets while loading items with an xhr?

**Comment by ianmcgregor** [comment]
Hi @morenoh149, as far as I know the browser should respect the cache headers even using XHR requests. Do you see the headers when you request the file directly in browser?

**Comment by morenoh149** [comment]
The video has these headers 
![s3-wont-cache](https://user-images.githubusercontent.com/587438/39492810-cfbb8fd6-4d5e-11e8-9de8-bd17b67921c7.png)
the initializer is `loader.js`, the video itself is actually webm. Do you think that discrepancy is why the browser wont cache it? The video is 100mb.

**Comment by ianmcgregor** [comment]
`200 OK (from disk cache)` indicates that the video was loaded from the browser cache without checking the remote server for a newer version (and then receiving a 304 as a result).

I guess there is still going to be some time delay loading the file from disk and decoding some frames but it shouldn't be going through the network.

**Comment by morenoh149** [comment]
hmm, after looking at this more closely the browser does seem to cache things. Tested with `disabled cache` off and using `cmd-R` and `cmd-shift-R`. The browser does go through assets-loader quicker with the cache and simply refreshing. It does a full reload when shift-refreshing.

When loading from cache you tend to get `200 OK (from disk cache)` and `206` from the development (express) server.

**Comment by ianmcgregor** [comment]
Cheers @morenoh149 glad we cleared that up
